{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sitename", "query": { "query": "label_values(up,sitename)" } }
  ]
 },
 "panels": [
  {
   "title": "General dashboards",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running SiteRM Versions",
   "type": "piechart",
   "description": "Running SiteRM Versions at Site.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (\n  running_version_info\n    and (timestamp(running_version_info) > time() - 300)\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Dashboards for SiteRM",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count of Alerts per Site (Critical)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (sitename) (\n  max_over_time(ALERTS{alertstate=\"firing\", software=\"SiteRM\", severity=\"critical\"}[5m])\n)",
     "legendFormat": "{{sitename}}"
    }
   ]
  },
  {
   "title": "Count of Alerts per Site (Warning)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (sitename) (\n  max_over_time(ALERTS{alertstate=\"firing\", severity=\"warning\"}[5m])\n)",
     "legendFormat": "{{sitename}}"
    }
   ]
  },
  { "title": "$sitename", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "sitename" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{sitename=\"$sitename\"}"
    }
   ]
  },
  {
   "title": "Total Critical Errors",
   "type": "stat",
   "description": "Count of Total Critical Errors",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", severity=\"critical\", sitename=\"$sitename\"}) or label_replace(0 * absent(ALERTS{sitename=\"$sitename\"}), \"sitename\", \"$sitename\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Warnings",
   "type": "stat",
   "description": "Count of Total Warnings at Site",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", severity=\"warning\", sitename=\"$sitename\"}) or label_replace(0 * absent(ALERTS{sitename=\"$sitename\"}), \"sitename\", \"$sitename\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VSW",
   "type": "stat",
   "description": "Count of all Virtual Switching Requests",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"vsw\", sitename=\"$sitename\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"vsw\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"vsw\", sitename=\"$sitename\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"vsw\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"vsw\", sitename=\"$sitename\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"vsw\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Not Active"
    }
   ]
  },
  {
   "title": "RST",
   "type": "stat",
   "description": "Count of all Routing Service Requests",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"rst\", sitename=\"$sitename\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"rst\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"rst\", sitename=\"$sitename\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"rst\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"rst\", sitename=\"$sitename\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"rst\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Not Active"
    }
   ]
  },
  {
   "title": "Kube",
   "type": "stat",
   "description": "Count of all Total Kube Port Requests",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"kube\", sitename=\"$sitename\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"kube\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"kube\", sitename=\"$sitename\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"kube\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"kube\", sitename=\"$sitename\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"kube\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Not Active"
    }
   ]
  },
  {
   "title": "SinglePort",
   "type": "stat",
   "description": "Count of all SinglePort Requests",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"singleport\", sitename=\"$sitename\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"singleport\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"singleport\", sitename=\"$sitename\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"singleport\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"singleport\", sitename=\"$sitename\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"singleport\", sitename=\"$sitename\"}),\n  \"sitename\", \n  \"$sitename\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "Not Active"
    }
   ]
  }
 ]
}