{
 "title": "ESNet",
 "tags": [
  "ESNet",
  "NSI"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Status of all endpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"ESNet\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{sitename=~\"ESNet\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"ESNet\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{sitename=~\"ESNet\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{sitename=~\"ESNet\"} - time()",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{sitename=~\"ESNet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{sitename=~\"ESNet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{sitename=~\"ESNet\"}) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{sitename=~\"ESNet\"}",
     "legendFormat": "{{job}} {{ phase }}"
    }
   ]
  }
 ]
}