{
 "title": "NRM_SCINET",
 "tags": [
  "NRM_SCINET",
  "SiteRM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Switches",
    "query": {
     "query": "label_values(interface_statistics{Key=\"ifHCInOctets\", sitename=\"NRM_SCINET\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SiteRM Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{sitename=\"NRM_SCINET\"}"
    }
   ]
  },
  {
   "title": "Total Critical Errors",
   "type": "stat",
   "description": "Count of Total Critical Errors",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", severity=\"critical\", sitename=\"NRM_SCINET\"}) or label_replace(0 * absent(ALERTS{sitename=\"NRM_SCINET\"}), \"sitename\", \"NRM_SCINET\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Warnings",
   "type": "stat",
   "description": "Count of Total Warnings at Site",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", severity=\"warning\", sitename=\"NRM_SCINET\"}) or label_replace(0 * absent(ALERTS{sitename=\"NRM_SCINET\"}), \"sitename\", \"NRM_SCINET\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total VSW Requests",
   "type": "stat",
   "description": "Count of all Total Virtual Switching Requests",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"vsw\", sitename=\"NRM_SCINET\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"vsw\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active VSW Requests",
   "type": "stat",
   "description": "Count of all Total Active Virtual Switching Requests",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"vsw\", sitename=\"NRM_SCINET\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"vsw\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Active VSW Requests",
   "type": "stat",
   "description": "Count of all Total Not Active Virtual Switching Requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"vsw\", sitename=\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"vsw\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status of all endpoints",
   "type": "state-timeline",
   "description": "List of endpoints that are queried by Prometheus.",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"NRM_SCINET\"}",
     "legendFormat": "{{job}} {{instance}}"
    },
    {
     "expr": "up{sitename=~\"NRM_SCINET\", realhostname=\"\"}",
     "legendFormat": "{{job}} {{instance}}"
    },
    {
     "expr": "up{sitename=~\"NRM_SCINET\", realhostname!=\"\"}",
     "legendFormat": "{{job}} {{realhostname}}"
    }
   ]
  },
  {
   "title": "Total RST Requests",
   "type": "stat",
   "description": "Count of all Total Routing Requests",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"rst\", sitename=\"NRM_SCINET\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"rst\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Routing Requests",
   "type": "stat",
   "description": "Count of all Total Active Routing Requests",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"rst\", sitename=\"NRM_SCINET\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"rst\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Active Routing Requests",
   "type": "stat",
   "description": "Count of all Total Not Active Routing Requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"rst\", sitename=\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"rst\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Kube Requests",
   "type": "stat",
   "description": "Count of all Total Kube Requests",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"kube\", sitename=\"NRM_SCINET\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"kube\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Kube Requests",
   "type": "stat",
   "description": "Count of all Total Kube Requests",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"kube\", sitename=\"NRM_SCINET\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"kube\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Active Kube Requests",
   "type": "stat",
   "description": "Count of all Total Not Active Kube Requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"kube\", sitename=\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"kube\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SinglePort Requests",
   "type": "stat",
   "description": "Count of all Total SinglePort Requests",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"singleport\", sitename=\"NRM_SCINET\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"singleport\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active SinglePort Requests",
   "type": "stat",
   "description": "Count of all Total SinglePort Requests",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"singleport\", sitename=\"NRM_SCINET\", network_status=\"activated\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"singleport\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Active SinglePort Requests",
   "type": "stat",
   "description": "Count of all Total Not Active SinglePort Requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (key0) (\n  network_status{action=\"singleport\", sitename=\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"}\n))\nor\nlabel_replace(\n  0 * absent(network_status{action=\"singleport\", sitename=\"NRM_SCINET\"}),\n  \"sitename\", \n  \"NRM_SCINET\", \n  \"\", \n  \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current active alerts/warnings",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", sitename=\"NRM_SCINET\"}[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICMP round trip time (V4)",
   "type": "timeseries",
   "description": "ICMP V4 Round Trip time from Prometheus hosts to SiteRM Frontend.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"NRM_SCINET\", ipversion=\"v4\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time (V6)",
   "type": "timeseries",
   "description": "ICMP V6 Round Trip time from Prometheus hosts to SiteRM Frontend.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"NRM_SCINET\", ipversion=\"v6\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "timeseries",
   "description": "Left lifetime for SSL Certificate validity. It will raise an alarm once less than a week is left.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{sitename=~\"NRM_SCINET\"} - time()",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "agent_cert{Key=~\"notAfter\", sitename=~\"NRM_SCINET\"} - time()",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "description": "HTTP Connection timeline.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{sitename=~\"NRM_SCINET\"}",
     "legendFormat": "{{job}} {{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "description": "HTTP Return Code. 200 OK, Anything else - failure. In case of failure - it will alert.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{sitename=~\"NRM_SCINET\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "state-timeline",
   "description": "Individual Service Status for Site Frontend and all Agents.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (servicename,service_state) (service_state{service_state=\"OK\",sitename=\"NRM_SCINET\"}) ",
     "legendFormat": "{{servicename}} {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Threads Runtime",
   "type": "timeseries",
   "description": "Individual SiteRM Thread Runtime. Only for debugging purposes of stuck processes. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_runtime{sitename=\"NRM_SCINET\"}",
     "legendFormat": "{{hostname}} {{servicename}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status",
   "type": "timeseries",
   "description": "All SiteRM Component's statuses are grouped by hostname and service state (only Running correctly) over time. 1 - service runs normally. Below 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename,hostname) (service_state{service_state=\"OK\", sitename=\"NRM_SCINET\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status (NOT OK)",
   "type": "timeseries",
   "description": "All SiteRM Component's statuses are grouped by hostname and service state over time. 1+OK - service runs normally. Below 1 or not OK - Service has failed for some reason.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename,hostname) (service_state{sitename=\"NRM_SCINET\", service_state!=\"OK\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}} {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Thread Memory Monitoring (VMS)",
   "type": "timeseries",
   "description": "SiteRM Frontend Memory statistics for all processes. Only for debugging purposes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{sitename=\"NRM_SCINET\", key=\"vms\"}",
     "legendFormat": "VMS {{servicename}} {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Thread Memory Monitoring (RSS)",
   "type": "timeseries",
   "description": "SiteRM Frontend Memory statistics for all processes. Only for debugging purposes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{sitename=\"NRM_SCINET\", key=~\"rss\"}",
     "legendFormat": "RSS {{servicename}} {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Disk Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_usage{sitename=\"NRM_SCINET\", key=\"UsePercentage\"}",
     "legendFormat": "{{filesystem}} {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Disk Inodes Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_usage{sitename=\"NRM_SCINET\", key=\"IUsePercentage\"}",
     "legendFormat": "{{filesystem}} {{hostname}}"
    }
   ]
  },
  {
   "title": "Running Versions grouped by Service,Hostname,Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": " sum by (servicename,hostname,version) (running_version_info{sitename=\"NRM_SCINET\"}) ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "piechart",
   "description": "Running SiteRM Versions at Site.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (version) (running_version_info{sitename=\"NRM_SCINET\"}) ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Able to receive monitoring data from DTNs",
   "type": "timeseries",
   "description": "Checks if Prometheus is able to receive monitoring data for this specific Site DTNs. 1 means OK, 0 means failure.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{sitename=\"NRM_SCINET\", software=\"SiteRM-Agent\"}",
     "legendFormat": "{{instance}} JOBID {{job}}"
    }
   ]
  },
  { "title": "SENSE Request States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Network Status VSW (ALL for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"vsw\", sitename=~\"NRM_SCINET\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status VSW (Not activated for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"vsw\", sitename=~\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status RST (ALL for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"rst\", sitename=~\"NRM_SCINET\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status RST (Not activated for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"rst\", sitename=~\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status Kube (ALL for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"kube\", sitename=~\"NRM_SCINET\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status Kube (Not activated for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"kube\", sitename=~\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status SinglePort (ALL for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"singleport\", sitename=~\"NRM_SCINET\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status SinglePort (Not activated for NRM_SCINET)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"singleport\", sitename=~\"NRM_SCINET\", network_status!=\"activated\", network_status!=\"unknown\", network_status!=\"unset\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  { "title": "$switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }, "repeat": "switch" },
  {
   "title": "Interface MTU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "interface_statistics{Key=\"ifMtu\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface ADMIN Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "interface_statistics{Key=\"ifAdminStatus\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Operation Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "interface_statistics{Key=\"ifOperStatus\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "QoS Requests from SENSE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "qos_status{key1=\"$switch\",valuetype=\"reservableCapacity\", sitename=\"NRM_SCINET\"}",
     "legendFormat": "{{vlan}} {{key1}} {{key2}}"
    }
   ]
  },
  {
   "title": "Interface Status (Octets In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInOctets\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Octets Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutOctets\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Discards In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifInDiscards\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Discards Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifOutDiscards\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Errors In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifInErrors\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Errors Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifOutErrors\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Unicast In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInUcastPkts\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Unicast Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutUcastPkts\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Multicast In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInMulticastPkts\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Multicast Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutMulticastPkts\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Broadcast In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInBroadcastPkts\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Broadcast Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutBroadcastPkts\", sitename=\"NRM_SCINET\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  }
 ]
}