{
 "title": "T3_FABRIC_LOSA",
 "tags": [
  "T3_FABRIC_LOSA",
  "SiteRM"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Switches",
    "query": {
     "query": "label_values(interface_statistics{Key=\"ifHCInOctets\", sitename=\"T3_FABRIC_LOSA\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SiteRM Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status of all endpoints",
   "type": "stat",
   "description": "List of endpoints that are queried by Prometheus.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"T3_FABRIC_LOSA\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "description": "Running SiteRM Versions at Site.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", software=\"SiteRM\", sitename=\"T3_FABRIC_LOSA\"}) or label_replace(0 * absent(ALERTS{sitename=\"T3_FABRIC_LOSA\"}), \"sitename\", \"T3_FABRIC_LOSA\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "piechart",
   "description": "Running SiteRM Versions at Site.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (version) (running_version_info{sitename=\"T3_FABRIC_LOSA\"}) ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "timeseries",
   "description": "Probe query success, failure. \n1 - OK, Below 1 - Failure, see for more details below.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"T3_FABRIC_LOSA\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time (V4)",
   "type": "timeseries",
   "description": "ICMP V4 Round Trip time from Prometheus hosts to SiteRM Frontend.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"T3_FABRIC_LOSA\", ipversion=\"v4\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time (V6)",
   "type": "timeseries",
   "description": "ICMP V6 Round Trip time from Prometheus hosts to SiteRM Frontend.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"T3_FABRIC_LOSA\", ipversion=\"v6\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "timeseries",
   "description": "Left lifetime for SSL Certificate validity. It will raise an alarm once less than a week is left.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{sitename=~\"T3_FABRIC_LOSA\"} - time()",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "agent_cert{Key=~\"notAfter\", sitename=~\"T3_FABRIC_LOSA\"} - time()",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "description": "HTTP Connection timeline.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{sitename=~\"T3_FABRIC_LOSA\"}",
     "legendFormat": "{{job}} {{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "description": "HTTP Return Code. 200 OK, Anything else - failure. In case of failure - it will alert.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{sitename=~\"T3_FABRIC_LOSA\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "state-timeline",
   "description": "Individual Service Status for Site Frontend and all Agents.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (servicename,service_state) (service_state{service_state=\"OK\",sitename=\"T3_FABRIC_LOSA\"}) ",
     "legendFormat": "{{servicename}} {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Threads Runtime",
   "type": "timeseries",
   "description": "Individual SiteRM Thread Runtime. Only for debugging purposes of stuck processes. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_runtime{sitename=\"T3_FABRIC_LOSA\"}",
     "legendFormat": "{{hostname}} {{servicename}}"
    }
   ]
  },
  {
   "title": "SiteRM LookUpService Not OK Status",
   "type": "timeseries",
   "description": "SiteRM LookUpService status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"LookUpService\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM ProvisioningService Not OK Status",
   "type": "timeseries",
   "description": "SiteRM ProvisioningService status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"ProvisioningService\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM SNMPMonitoring Not OK Status",
   "type": "timeseries",
   "description": "SiteRM SNMPMonitoring status over time. No data - Service runs normally. 1 - Service has failed for some reason. It will not alert as SNMP is not mandatory.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"SNMPMonitoring\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Agent Not OK Status",
   "type": "timeseries",
   "description": "All SiteRM Agents' status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Agent\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Debugger Not OK Status",
   "type": "timeseries",
   "description": "All SiteRM Debugger's status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Debugger\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Ruler Not OK Status",
   "type": "timeseries",
   "description": "All SiteRM Rulers' status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Ruler\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status",
   "type": "timeseries",
   "description": "All SiteRM Component's statuses are grouped by hostname and service state (only Running correctly) over time. 1 - service runs normally. Below 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename,hostname) (service_state{service_state=\"OK\", sitename=\"T3_FABRIC_LOSA\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status (NOT OK)",
   "type": "timeseries",
   "description": "All SiteRM Component's statuses are grouped by hostname and service state over time. 1+OK - service runs normally. Below 1 or not OK - Service has failed for some reason.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename,hostname) (service_state{sitename=\"T3_FABRIC_LOSA\", service_state!=\"OK\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}} {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Thread Memory Monitoring (VMS)",
   "type": "timeseries",
   "description": "SiteRM Frontend Memory statistics for all processes. Only for debugging purposes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{sitename=\"T3_FABRIC_LOSA\", key=\"vms\"}",
     "legendFormat": "VMS {{servicename}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Thread Memory Monitoring (RSS)",
   "type": "timeseries",
   "description": "SiteRM Frontend Memory statistics for all processes. Only for debugging purposes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{sitename=\"T3_FABRIC_LOSA\", key=~\"rss\"}",
     "legendFormat": "RSS {{servicename}}"
    }
   ]
  },
  {
   "title": "Running Versions grouped by Service,Hostname,Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": " sum by (servicename,hostname,version) (running_version_info{sitename=\"T3_FABRIC_LOSA\"}) ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Able to receive monitoring data from DTNs",
   "type": "timeseries",
   "description": "Checks if Prometheus is able to receive monitoring data for this specific Site DTNs. 1 means OK, 0 means failure.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{sitename=\"T3_FABRIC_LOSA\", software=\"SiteRM-Agent\"}",
     "legendFormat": "{{instance}} JOBID {{job}}"
    }
   ]
  },
  { "title": "SENSE Request States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Network Status VSW (ALL for T3_FABRIC_LOSA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"vsw\", sitename=~\"T3_FABRIC_LOSA\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status RST (ALL for T3_FABRIC_LOSA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"rst\", sitename=~\"T3_FABRIC_LOSA\", network_status!=\"unknown\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status VSW (Not activated for T3_FABRIC_LOSA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"vsw\", sitename=~\"T3_FABRIC_LOSA\", network_status!=\"activated\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status VSW (Not activated for T3_FABRIC_LOSA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"rst\", sitename=~\"T3_FABRIC_LOSA\", network_status!=\"activated\", network_status!=\"unknown\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Software Router Monitoring (VPP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 }
  },
  {
   "title": "VPP Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_uptime{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total (sub-)interfaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (interface) (interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\",interface!~\".*\\\\..*\",software=\"VPP\"}))",
     "legendFormat": "interfaces"
    },
    {
     "expr": "count(count by (interface) (interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\",interface=~\".*\\\\..*\",software=\"VPP\"}))",
     "legendFormat": "sub-ifaces"
    },
    {
     "expr": "count(count by (interface) (interfaces_rx_packets{instance=\"$instance\",interface=~\"tap[0-9]+\",software=\"VPP\"}))",
     "legendFormat": "tap"
    },
    {
     "expr": "count(count by (interface) (interfaces_rx_packets{instance=\"$instance\",interface=~\"vxlan_.*\",software=\"VPP\"}))",
     "legendFormat": "vxlan"
    },
    {
     "expr": "count(count by (interface) (interfaces_rx_packets{instance=\"$instance\",interface=~\"geneve_.*\",software=\"VPP\"}))",
     "legendFormat": "geneve"
    }
   ]
  },
  {
   "title": "Total traffic (bits/sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(interfaces_tx_bytes{interface!~\".*\\\\..*\",sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[5m])*8)",
     "legendFormat": "TX"
    },
    {
     "expr": "sum by (instance) (rate(interfaces_rx_bytes{interface!~\".*\\\\..*\",sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[5m])*8)",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Input L2 packets/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(err{node=~\"(arp|bond|dpdk|virtio|ethernet|l2)-input$\", sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index, error)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Input L3 packets/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(err{node=~\"(ip4|ip6|mpls|vxlan4|vxlan6)-input(-.*)?$\", sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index, error)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Worker CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (index) (sys_vector_rate_per_worker{software=\"VPP\",thread=\"0\",sitename=\"T3_FABRIC_LOSA\"})/256 ",
     "legendFormat": "Thread {{index}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"} / mem_total{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"} ",
     "legendFormat": "{{heap}}"
    },
    {
     "expr": "buffer_pools_used{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"} / (buffer_pools_used{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"} + buffer_pools_available{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"})",
     "legendFormat": "buffers {{pool}}"
    }
   ]
  },
  {
   "title": "Total Packetloss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(interfaces_rx_miss{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[2m])) / sum by (job) (rate(interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[2m]))",
     "legendFormat": "RX Loss"
    },
    {
     "expr": "sum by (job) (rate(interfaces_tx_error{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[60s])) / sum by (job) (rate(interfaces_tx_packets{sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[60s]))",
     "legendFormat": "TX Loss"
    }
   ]
  },
  {
   "title": "Total traffic (packets/sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(interfaces_tx_packets{interface!~\".*\\\\..*\",sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[5m]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum by (job) (rate(interfaces_rx_packets{interface!~\".*\\\\..*\",sitename=\"T3_FABRIC_LOSA\",software=\"VPP\"}[5m]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Interface L2 Bits/Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(interfaces_rx_bytes{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[5m])) without (thread, index) * 8 ",
     "legendFormat": "{{interface}} RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_bytes{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[5m])) without (thread, index) * 8",
     "legendFormat": "{{interface}} TX"
    },
    {
     "expr": "sum(irate(interfaces_rx_bytes{instance=\"$instance\", interface=~\"$interface\", software=\"VPP\"}[5m])) without (thread, index, interface) * 8",
     "legendFormat": "Total RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_bytes{instance=\"$instance\", interface=~\"$interface\", software=\"VPP\"}[5m])) without (thread, index, interface) * 8\n",
     "legendFormat": "Total TX"
    }
   ]
  },
  {
   "title": "Interface Packets/Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[5m])) without (thread, index)\n",
     "legendFormat": "{{interface}} RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[5m])) without (thread, index)\n",
     "legendFormat": "{{interface}} TX"
    },
    {
     "expr": "sum(irate(interfaces_rx_packets{instance=\"$instance\", interface=~\"$interface\", software=\"VPP\"}[5m])) without (thread, index, interface)\n",
     "legendFormat": "Total RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_packets{instance=\"$instance\", interface=~\"$interface\", software=\"VPP\"}[5m])) without (thread, index, interface)\n",
     "legendFormat": "Total TX"
    }
   ]
  },
  {
   "title": "Sub-iface L2 Bits/Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(interfaces_rx_bytes{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index) * 8\n",
     "legendFormat": "{{interface}} RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_bytes{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index) * 8\n",
     "legendFormat": "{{interface}} TX"
    }
   ]
  },
  {
   "title": "Sub-iface Packets/Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index)\n",
     "legendFormat": "{{interface}} RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index)\n",
     "legendFormat": "{{interface}} TX"
    }
   ]
  },
  {
   "title": "Interface RX Miss / TX Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(interfaces_rx_miss{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index) * 100 / sum(irate(interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m]) > 0) without (thread, index)\n",
     "legendFormat": "{{interface}} RX Loss"
    },
    {
     "expr": "sum(irate(interfaces_tx_error{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (thread, index) / sum(irate(interfaces_tx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m]) > 0) without (thread, index)\n",
     "legendFormat": "{{interface}} TX Loss"
    }
   ]
  },
  {
   "title": "Interface Packets/Sec (thread)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(interfaces_rx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (index)\n",
     "legendFormat": "{{interface}} Thread {{thread}} RX"
    },
    {
     "expr": "sum(irate(interfaces_tx_packets{sitename=\"T3_FABRIC_LOSA\", software=\"VPP\"}[2m])) without (index)\n",
     "legendFormat": "{{interface}} Thread {{thread}} TX"
    }
   ]
  }
 ]
}