{
 "title": "T3_FABRIC_CIEN",
 "tags": [
  "T3_FABRIC_CIEN",
  "SiteRM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "switch",
    "label": "Switches",
    "query": {
     "query": "label_values(interface_statistics{Key=\"ifHCInOctets\", sitename=\"T3_FABRIC_CIEN\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SiteRM Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status of all endpoints",
   "type": "stat",
   "description": "List of endpoints that are queried by Prometheus.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"T3_FABRIC_CIEN\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Total Errors/Warnings",
   "type": "stat",
   "description": "Running SiteRM Versions at Site.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", sitename=\"T3_FABRIC_CIEN\"}) or label_replace(0 * absent(ALERTS{sitename=\"T3_FABRIC_CIEN\"}), \"sitename\", \"T3_FABRIC_CIEN\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "piechart",
   "description": "Running SiteRM Versions at Site.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (version) (running_version_info{sitename=\"T3_FABRIC_CIEN\"}) ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Current active alerts/warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max_over_time(ALERTS{alertstate=\"firing\", sitename=\"T3_FABRIC_CIEN\"}[5m]) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "timeseries",
   "description": "Probe query success, failure. \n1 - OK, Below 1 - Failure, see for more details below.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"T3_FABRIC_CIEN\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time (V4)",
   "type": "timeseries",
   "description": "ICMP V4 Round Trip time from Prometheus hosts to SiteRM Frontend.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"T3_FABRIC_CIEN\", ipversion=\"v4\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time (V6)",
   "type": "timeseries",
   "description": "ICMP V6 Round Trip time from Prometheus hosts to SiteRM Frontend.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"T3_FABRIC_CIEN\", ipversion=\"v6\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "timeseries",
   "description": "Left lifetime for SSL Certificate validity. It will raise an alarm once less than a week is left.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{sitename=~\"T3_FABRIC_CIEN\"} - time()",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "agent_cert{Key=~\"notAfter\", sitename=~\"T3_FABRIC_CIEN\"} - time()",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "description": "HTTP Connection timeline.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{sitename=~\"T3_FABRIC_CIEN\"}",
     "legendFormat": "{{job}} {{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "description": "HTTP Return Code. 200 OK, Anything else - failure. In case of failure - it will alert.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{sitename=~\"T3_FABRIC_CIEN\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "state-timeline",
   "description": "Individual Service Status for Site Frontend and all Agents.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (servicename,service_state) (service_state{service_state=\"OK\",sitename=\"T3_FABRIC_CIEN\"}) ",
     "legendFormat": "{{servicename}} {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Threads Runtime",
   "type": "timeseries",
   "description": "Individual SiteRM Thread Runtime. Only for debugging purposes of stuck processes. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_runtime{sitename=\"T3_FABRIC_CIEN\"}",
     "legendFormat": "{{hostname}} {{servicename}}"
    }
   ]
  },
  {
   "title": "SiteRM LookUpService Not OK Status",
   "type": "timeseries",
   "description": "SiteRM LookUpService status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"LookUpService\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM ProvisioningService Not OK Status",
   "type": "timeseries",
   "description": "SiteRM ProvisioningService status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"ProvisioningService\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM SNMPMonitoring Not OK Status",
   "type": "timeseries",
   "description": "SiteRM SNMPMonitoring status over time. No data - Service runs normally. 1 - Service has failed for some reason. It will not alert as SNMP is not mandatory.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"SNMPMonitoring\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Agent Not OK Status",
   "type": "timeseries",
   "description": "All SiteRM Agents' status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Agent\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Debugger Not OK Status",
   "type": "timeseries",
   "description": "All SiteRM Debugger's status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Debugger\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Ruler Not OK Status",
   "type": "timeseries",
   "description": "All SiteRM Rulers' status over time. No data - Service runs normally. 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Ruler\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status",
   "type": "timeseries",
   "description": "All SiteRM Component's statuses are grouped by hostname and service state (only Running correctly) over time. 1 - service runs normally. Below 1 - Service has failed for some reason. If failure - it will alert.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename,hostname) (service_state{service_state=\"OK\", sitename=\"T3_FABRIC_CIEN\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status (NOT OK)",
   "type": "timeseries",
   "description": "All SiteRM Component's statuses are grouped by hostname and service state over time. 1+OK - service runs normally. Below 1 or not OK - Service has failed for some reason.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (service_state,servicename,hostname) (service_state{sitename=\"T3_FABRIC_CIEN\", service_state!=\"OK\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}} {{hostname}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Thread Memory Monitoring (VMS)",
   "type": "timeseries",
   "description": "SiteRM Frontend Memory statistics for all processes. Only for debugging purposes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{sitename=\"T3_FABRIC_CIEN\", key=\"vms\"}",
     "legendFormat": "VMS {{servicename}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Thread Memory Monitoring (RSS)",
   "type": "timeseries",
   "description": "SiteRM Frontend Memory statistics for all processes. Only for debugging purposes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{sitename=\"T3_FABRIC_CIEN\", key=~\"rss\"}",
     "legendFormat": "RSS {{servicename}}"
    }
   ]
  },
  {
   "title": "SiteRM FE Disk Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_usage{sitename=\"T3_FABRIC_CIEN\", key=\"UsePercentage\"}",
     "legendFormat": "{{filesystem}} "
    }
   ]
  },
  {
   "title": "SiteRM FE Disk Inodes Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_usage{sitename=\"T3_FABRIC_CIEN\", key=\"IUsePercentage\"}",
     "legendFormat": "{{filesystem}} "
    }
   ]
  },
  {
   "title": "Running Versions grouped by Service,Hostname,Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": " sum by (servicename,hostname,version) (running_version_info{sitename=\"T3_FABRIC_CIEN\"}) ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Able to receive monitoring data from DTNs",
   "type": "timeseries",
   "description": "Checks if Prometheus is able to receive monitoring data for this specific Site DTNs. 1 means OK, 0 means failure.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{sitename=\"T3_FABRIC_CIEN\", software=\"SiteRM-Agent\"}",
     "legendFormat": "{{instance}} JOBID {{job}}"
    }
   ]
  },
  { "title": "SENSE Request States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Network Status VSW (ALL for T3_FABRIC_CIEN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"vsw\", sitename=~\"T3_FABRIC_CIEN\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status RST (ALL for T3_FABRIC_CIEN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"rst\", sitename=~\"T3_FABRIC_CIEN\", network_status!=\"unknown\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status VSW (Not activated for T3_FABRIC_CIEN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"vsw\", sitename=~\"T3_FABRIC_CIEN\", network_status!=\"activated\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  {
   "title": "Network Status VSW (Not activated for T3_FABRIC_CIEN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_status{action=\"rst\", sitename=~\"T3_FABRIC_CIEN\", network_status!=\"activated\", network_status!=\"unknown\"} > 0",
     "legendFormat": "{{ key0}} {{key1}} {{key2}} {{network_status}}"
    }
   ]
  },
  { "title": "$switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }, "repeat": "switch" },
  {
   "title": "Interface MTU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "interface_statistics{Key=\"ifMtu\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface ADMIN Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "interface_statistics{Key=\"ifAdminStatus\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Operation Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "interface_statistics{Key=\"ifOperStatus\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "QoS Requests from SENSE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "qos_status{key1=\"$switch\",valuetype=\"reservableCapacity\", sitename=\"T3_FABRIC_CIEN\"}",
     "legendFormat": "{{vlan}} {{key1}} {{key2}}"
    }
   ]
  },
  {
   "title": "Interface Status (Octets In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInOctets\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Octets Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutOctets\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Discards In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifInDiscards\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Discards Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifOutDiscards\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Errors In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifInErrors\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Errors Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifOutErrors\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Unicast In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInUcastPkts\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Unicast Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutUcastPkts\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Multicast In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInMulticastPkts\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Multicast Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutMulticastPkts\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Broadcast In)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCInBroadcastPkts\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Interface Status (Broadcast Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(interface_statistics{Key=\"ifHCOutBroadcastPkts\", sitename=\"T3_FABRIC_CIEN\", hostname=\"$switch\"}[5m])*8",
     "legendFormat": "{{ifDescr}} ({{ifAlias}})"
    }
   ]
  }
 ]
}