{
 "title": "T3_US_FIU",
 "tags": [
  "T3_US_FIU",
  "SiteRM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Status of all endpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{sitename=~\"T3_US_FIU\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{sitename=~\"T3_US_FIU\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ICMP round trip time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{sitename=~\"T3_US_FIU\"}) by (Sitename, phase) > 0",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{sitename=~\"T3_US_FIU\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{sitename=~\"T3_US_FIU\"} - time()",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{sitename=~\"T3_US_FIU\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{sitename=~\"T3_US_FIU\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{sitename=~\"T3_US_FIU\"}) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{sitename=~\"T3_US_FIU\"}",
     "legendFormat": "{{job}} {{ phase }}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (servicename,service_state) (service_state{service_state=\"OK\",sitename=\"T3_US_FIU\"}) ",
     "legendFormat": "{{servicename}} {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Agent Not OK Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Agent\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Debugger Not OK Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Debugger\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM LookUpService Not OK Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"LookUpService\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM PolicyService Not OK Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"PolicyService\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM ProvisioningService Not OK Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"ProvisioningService\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Ruler Not OK Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state!=\"OK\",servicename=\"Ruler\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{service_state=\"OK\", sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  },
  {
   "title": "SiteRM Component Status (Any Status)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum by (service_state,servicename) (service_state{sitename=\"T3_US_FIU\"}) > 0",
     "legendFormat": "{{servicename}} - {{service_state}}"
    }
   ]
  }
 ]
}