# This is the default configuration used by SENSE.
# Only adding default configuration parameters, which
# are not automatically scanned, parsed from SiteFE configs
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
rule_files:
  - /etc/prometheus/alerts.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
- job_name: PACWAVE_SNMPMon
  metrics_path: /metrics
  relabel_configs:
  - replacement: NSI_PACWAVE
    source_labels:
    - __address__
    target_label: nsisitename
  - replacement: NSI-SNMPMon
    source_labels:
    - __address__
    target_label: software
  - replacement: 37.876
    source_labels:
    - __address__
    target_label: latitude
  - replacement: -122.253
    source_labels:
    - __address__
    target_label: longitude
  scheme: https
  scrape_interval: 30s
  static_configs:
  - targets:
    - nsi-snmpmon-cenic.nrp-nautilus.io
  tls_config:
    cert_file: /etc/tls/tls.crt
    insecure_skip_verify: true
    key_file: /etc/tls/tls.key
- job_name: Internet2_SNMPMon
  metrics_path: /metrics
  relabel_configs:
  - replacement: Internet2
    source_labels:
    - __address__
    target_label: nsisitename
  - replacement: NSI-SNMPMon
    source_labels:
    - __address__
    target_label: software
  - replacement: 37.876
    source_labels:
    - __address__
    target_label: latitude
  - replacement: -122.253
    source_labels:
    - __address__
    target_label: longitude
  scheme: https
  scrape_interval: 30s
  static_configs:
  - targets:
    - nsi-snmpmon-internet2.nrp-nautilus.io
  tls_config:
    cert_file: /etc/tls/tls.crt
    insecure_skip_verify: true
    key_file: /etc/tls/tls.key
