# This is the default configuration used by SENSE.
# Only adding default configuration parameters, which
# are not automatically scanned, parsed from SiteFE configs
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#      - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
- job_name: PACWAVE_SNMPMon
  metrics_path: /metrics
  relabel_configs:
  - replacement: NSI_PACWAVE
    source_labels:
    - __address__
    target_label: sitename
  - replacement: NSI-SNMPMon
    source_labels:
    - __address__
    target_label: software
  - replacement: 37.876
    source_labels:
    - __address__
    target_label: latitude
  - replacement: -122.253
    source_labels:
    - __address__
    target_label: longitude
  scheme: https
  scrape_interval: 30s
  static_configs:
  - targets:
    - nsi-snmpmon-cenic.nrp-nautilus.io
  tls_config:
    cert_file: /etc/siterm-cert.pem
    insecure_skip_verify: true
    key_file: /etc/siterm-privkey.pem
- job_name: ESnet_SNMPMon
  metrics_path: /metrics
  relabel_configs:
  - replacement: ESnet
    source_labels:
    - __address__
    target_label: sitename
  - replacement: NSI-SNMPMon
    source_labels:
    - __address__
    target_label: software
  - replacement: 37.876
    source_labels:
    - __address__
    target_label: latitude
  - replacement: -122.253
    source_labels:
    - __address__
    target_label: longitude
  scheme: https
  scrape_interval: 30s
  static_configs:
  - targets:
    - nsi-snmpmon-esnet.nrp-nautilus.io
  tls_config:
    cert_file: /etc/siterm-cert.pem
    insecure_skip_verify: true
    key_file: /etc/siterm-privkey.pem
- job_name: Internet2_SNMPMon
  metrics_path: /metrics
  relabel_configs:
  - replacement: Internet2
    source_labels:
    - __address__
    target_label: sitename
  - replacement: NSI-SNMPMon
    source_labels:
    - __address__
    target_label: software
  - replacement: 37.876
    source_labels:
    - __address__
    target_label: latitude
  - replacement: -122.253
    source_labels:
    - __address__
    target_label: longitude
  scheme: https
  scrape_interval: 30s
  static_configs:
  - targets:
    - nsi-snmpmon-internet2.nrp-nautilus.io
  tls_config:
    cert_file: /etc/siterm-cert.pem
    insecure_skip_verify: true
    key_file: /etc/siterm-privkey.pem
- job_name: T2_US_SDSC_POD_0
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-01-111.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_1
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-02-111.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_2
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-03-111.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_3
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-04-111.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_4
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-01-112.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_5
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-02-112.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_6
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-03-112.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_7
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-04-112.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_8
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-01-113.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_9
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-02-113.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_10
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-03-113.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_11
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-04-113.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_12
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-01-114.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_13
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-02-114.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_14
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-03-114.sdsc.optiputer.net:9100
- job_name: T2_US_SDSC_POD_15
  relabel_configs:
  - replacement: T2_US_SDSC
    source_labels:
    - __address__
    target_label: sitename
  - replacement: SiteRM-Agent
    source_labels:
    - __address__
    target_label: software
  static_configs:
  - targets:
    - xrootd-sense-ucsd-04-114.sdsc.optiputer.net:9100
- job_name: vpp
  metrics_path: /metrics
  relabel_configs:
  - replacement: T3_FABRIC_CERN
    source_labels:
    - __address__
    target_label: sitename
  - replacement: FRR_VPP
    source_labels:
    - __address__
    target_label: software
  - source_labels:
    - __param_target
    target_label: instance
  static_configs:
  - targets:
    - "[2602:fcfb:1d:fff0::2]:1234"


# Any manual added scrap configs will remain;
# This is what SENSE will add into scrape configuration for FE Prometheus:
#  - job_name: <SITENAME>_<TYPE>
#    scrape_interval: 30s
#    static_configs:
#      - targets: ['<SITE_FE_URI>']
#    scheme: https
#    metrics_path: /<SITENAME>/sitefe/json/frontend/metrics
#    tls_config:
#      cert_file: /etc/prometheus/cert.pem
#      key_file: /etc/prometheus/privkey.pem
#      insecure_skip_verify: true

# This is what it will add for DTN, if this is enabled in DTN Yaml file.
#  - job_name: <SITENAME>_<TYPE>_<INCREMENTAL_INTEGER>
#    static_configs:
#      - targets: ['<AGENT_NODE_EXPORTER_ENDPOINT>']
